steps:
  - script: |
      . build_variables.sh
    displayName: 'Set variables'
  - script: |
      . build_docker.sh
    displayName: 'Build'
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: stratsysContainerRegistry
  - script: |
      . push_dockerimage.sh
    displayName: 'Push docker image'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  - task: Docker@2
    displayName: Logout from ACR
    inputs:
      command: logout
      containerRegistry: stratsysContainerRegistry
  - script: |
      . remove_dockerimage.sh
    displayName: 'Remove built image'
variables:
  - name: RELEASE_BRANCH
    value: $(Build.SourceBranchName)
  - name: COMPLETE_RELEASE_BRANCH
    value: $(Build.SourceBranch)
  - name: GIT_COMMIT_SHA
    value: $(Build.SourceVersion)
  - group: "Azure container registry - stratsys"
trigger:
  - master
pool: "Linux-docker"
